import { env } from "../../../config/env.js";
import { BadRequestError } from "../../../utils/errors.js";
import type { OAuthProfile } from "./types.js";

const AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth";
const TOKEN_URL = "https://oauth2.googleapis.com/token";
const USERINFO_URL = "https://openidconnect.googleapis.com/v1/userinfo";
const SCOPES = ["openid", "email", "profile"];

// Build the consent-screen URL. `state` and PKCE `challenge` are generated by
// the caller and echoed back on the callback.
export function buildGoogleAuthUrl(state: string, challenge: string): string {
  const params = new URLSearchParams({
    client_id: env.GOOGLE_CLIENT_ID,
    redirect_uri: env.GOOGLE_REDIRECT_URI,
    response_type: "code",
    scope: SCOPES.join(" "),
    state,
    code_challenge: challenge,
    code_challenge_method: "S256",
    access_type: "offline",
    include_granted_scopes: "true",
    prompt: "consent",
  });
  return `${AUTH_URL}?${params.toString()}`;
}

interface GoogleTokenResponse {
  access_token: string;
  expires_in: number;
  refresh_token?: string;
  scope: string;
  token_type: string;
  id_token: string;
}

interface GoogleUserInfo {
  sub: string;
  email?: string;
  email_verified?: boolean;
  name?: string;
  given_name?: string;
  picture?: string;
}

async function exchangeCode(
  code: string,
  codeVerifier: string,
): Promise<GoogleTokenResponse> {
  const res = await fetch(TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      client_id: env.GOOGLE_CLIENT_ID,
      client_secret: env.GOOGLE_CLIENT_SECRET,
      code,
      grant_type: "authorization_code",
      redirect_uri: env.GOOGLE_REDIRECT_URI,
      code_verifier: codeVerifier,
    }),
  });
  if (!res.ok) {
    throw new BadRequestError("Failed to exchange Google authorization code");
  }
  return (await res.json()) as GoogleTokenResponse;
}

async function fetchUserInfo(accessToken: string): Promise<GoogleUserInfo> {
  const res = await fetch(USERINFO_URL, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  if (!res.ok) {
    throw new BadRequestError("Failed to fetch Google user profile");
  }
  return (await res.json()) as GoogleUserInfo;
}

export async function getGoogleProfile(
  code: string,
  codeVerifier: string,
): Promise<OAuthProfile> {
  const tokens = await exchangeCode(code, codeVerifier);
  const info = await fetchUserInfo(tokens.access_token);

  const email = info.email?.toLowerCase() ?? null;
  const usernameSeed = email ? email.split("@")[0]! : info.sub;

  return {
    provider: "GOOGLE",
    providerUserId: info.sub,
    email,
    emailVerified: Boolean(info.email_verified),
    displayName: info.name || info.given_name || usernameSeed,
    username: usernameSeed,
    avatar: info.picture ?? null,
    // We do not persist Google tokens (no offline API use); kept transient.
    accessToken: tokens.access_token,
    refreshToken: tokens.refresh_token ?? null,
    scopes: tokens.scope ? tokens.scope.split(" ") : SCOPES,
    expiresAt: tokens.expires_in
      ? new Date(Date.now() + tokens.expires_in * 1000)
      : null,
  };
}
